# Generated by Django 5.0.6 on 2024-11-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vesselreading',
            table='vessel_readings',
        ),
    ]
