# Generated by Django 5.0.6 on 2024-11-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_vesselreading_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselreading',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='vesselreading',
            table=None,
        ),
    ]
