# Generated by Django 5.0.6 on 2024-11-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_vesselreading_level_alter_vesselreading_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselreading',
            name='level',
            field=models.FloatField(),
        ),
    ]
